using System.Globalization;
using System.Text.Json;
using System.Xml.Linq;

// Edits inert archive XML only. Every candidate still passes ArchivePolicy and
// a real Compute solve before the app can adopt it. No arbitrary XML or code.
public static class GraphEdits
{
    public static void Apply(XDocument xml, JsonElement edits)
    {
        if (edits.ValueKind != JsonValueKind.Array || edits.GetArrayLength() > 24) throw new Exception("At most 24 graph edits are allowed per test.");
        var definition = xml.Descendants("chunk").Single(x => Name(x) == "DefinitionObjects");
        var objects = definition.Element("chunks") ?? throw new Exception("Missing definition objects.");
        // Only remove groups generated by our bridge, preserving user groups.
        foreach (var o in objects.Elements("chunk").ToArray())
        {
            var c = Chunk(o, "Container");
            if (Value(o, "Name") == "Group" && Value(c, "Description") == "Compute preview" &&
                (Value(c, "NickName").StartsWith("RH_IN:") || Value(c, "NickName").StartsWith("RH_OUT:"))) o.Remove();
        }
        foreach (var edit in edits.EnumerateArray())
        {
            var op = Text(edit, "op");
            var nodeId = Text(edit, "nodeId");
            var obj = objects.Elements("chunk").SingleOrDefault(o => Value(Chunk(o, "Container"), "InstanceGuid") == nodeId)
                ?? throw new Exception("Edit references an unknown node.");
            if (Value(obj, "Name") == "Group") throw new Exception("Group editing is not enabled.");
            var c = Chunk(obj, "Container")!;
            switch (op)
            {
                case "rename":
                    Set(c, "NickName", Limited(edit, "text", 100), "gh_string", 10); break;
                case "slider":
                    var slider = Chunk(c, "Slider") ?? throw new Exception("This node is not a number slider.");
                    var min = OptionalNumber(edit, "min") ?? Number(slider, "Min");
                    var max = OptionalNumber(edit, "max") ?? Number(slider, "Max");
                    var value = OptionalNumber(edit, "value") ?? Number(slider, "Value");
                    if (min > max || value < min || value > max || Math.Abs(min) > 1e6 || Math.Abs(max) > 1e6) throw new Exception("Invalid slider bounds or value.");
                    Set(slider, "Min", min); Set(slider, "Max", max); Set(slider, "Value", value); break;
                case "panel":
                    if (Value(obj, "GUID") != "59e0b89a-e487-49f8-bab8-b5bab16be14c") throw new Exception("This node is not a Panel.");
                    Set(c, "UserText", Limited(edit, "text", 1000), "gh_string", 10); break;
                case "expression":
                    var input = Input(c, Integer(edit, "input"));
                    var expression = Limited(edit, "text", 256);
                    if (!ArithmeticExpression.IsAllowed(expression)) throw new Exception("Only bounded arithmetic input expressions are enabled.");
                    Set(input, "InternalExpression", expression, "gh_string", 10); break;
                case "connect":
                case "disconnect":
                    var target = Input(c, Integer(edit, "input"));
                    var sourceId = Text(edit, "sourceNode");
                    var source = objects.Elements("chunk").SingleOrDefault(o => Value(Chunk(o, "Container"), "InstanceGuid") == sourceId)
                        ?? throw new Exception("Unknown source node.");
                    var sourcePort = Output(Chunk(source, "Container")!, Integer(edit, "output"));
                    var sources = Items(target, "Source").Select(x => x.Value).ToList();
                    if (op == "connect") { if (!sources.Contains(sourcePort)) sources.Add(sourcePort); }
                    else sources.RemoveAll(s => s == sourcePort);
                    Sources(target, sources); break;
                case "clone":
                    if (objects.Elements().Count() >= 480) throw new Exception("Not enough capacity to add another node.");
                    var newId = Text(edit, "newId");
                    if (!Guid.TryParse(newId, out _) || objects.Elements("chunk").Any(o => Value(Chunk(o, "Container"), "InstanceGuid") == newId)) throw new Exception("A clone needs a new unique GUID.");
                    var clone = new XElement(obj);
                    var cloneContainer = Chunk(clone, "Container")!;
                    foreach (var id in cloneContainer.Descendants("item").Where(x => Name(x) == "InstanceGuid")) id.Value = Guid.NewGuid().ToString();
                    Set(cloneContainer, "InstanceGuid", newId, "gh_guid", 9);
                    foreach (var owner in cloneContainer.DescendantsAndSelf("chunk").Where(x => Items(x, "Source").Any() || Items(x, "SourceCount").Any()).ToArray()) Sources(owner, []);
                    if (Text(edit, "text").Length > 0) Set(cloneContainer, "NickName", Limited(edit, "text", 100), "gh_string", 10);
                    var attributes = Chunk(cloneContainer, "Attributes");
                    if (attributes != null)
                        foreach (var p in attributes.Descendants("item").Where(x => Name(x) is "Bounds" or "Pivot"))
                            foreach (var axis in new[] { "X", "Y" })
                                if (p.Element(axis) is { } coordinate && double.TryParse(coordinate.Value, CultureInfo.InvariantCulture, out var n)) coordinate.Value = (n + (axis == "X" ? 200 : 120)).ToString("R", CultureInfo.InvariantCulture);
                    objects.Add(clone); break;
                case "remove":
                    var deletedPorts = GraphReader.Read([obj]).nodes.Single().outputs.Select(p => p.id).ToHashSet();
                    foreach (var owner in objects.Descendants("chunk").Where(x => Items(x, "Source").Any()).ToArray())
                        Sources(owner, Items(owner, "Source").Select(x => x.Value).Where(id => !deletedPorts.Contains(id)).ToArray());
                    foreach (var group in objects.Elements("chunk").Where(o => Value(o, "Name") == "Group"))
                    {
                        var gc = Chunk(group, "Container")!;
                        foreach (var id in Items(gc, "ID").Where(x => x.Value == nodeId).ToArray()) id.Remove();
                        var members = Items(gc, "ID").ToArray();
                        for (var i = 0; i < members.Length; i++) members[i].SetAttributeValue("index", i);
                        Set(gc, "ID_Count", members.Length.ToString(), "gh_int32", 3);
                    }
                    obj.Remove(); break;
                default: throw new Exception("Unknown graph edit operation.");
            }
        }
        var all = objects.Elements("chunk").ToArray();
        for (var i = 0; i < all.Length; i++) all[i].SetAttributeValue("index", i);
        Set(definition, "ObjectCount", all.Length.ToString(), "gh_int32", 3);
        var graph = GraphReader.Read(all);
        if (graph.notes.Length > 0) throw new Exception("The edited graph has unresolved wires or duplicate IDs.");
        var edges = graph.wires.GroupBy(w => w.sourceNode).ToDictionary(g => g.Key, g => g.Select(w => w.targetNode).Distinct().ToArray());
        var active = new HashSet<string>(); var done = new HashSet<string>();
        bool Cycle(string id) { if (active.Contains(id)) return true; if (!done.Add(id)) return false; active.Add(id); foreach (var next in edges.GetValueOrDefault(id, [])) if (Cycle(next)) return true; active.Remove(id); return false; }
        if (graph.nodes.Any(n => Cycle(n.id))) throw new Exception("A graph edit introduced a dependency cycle.");
        foreach (var list in xml.Descendants().Where(x => x.Name == "items" || x.Name == "chunks")) list.SetAttributeValue("count", list.Elements().Count());
    }
    static string Name(XElement e) => (string?)e.Attribute("name") ?? "";
    static IEnumerable<XElement> Items(XElement? e, string name) => e?.Element("items")?.Elements("item").Where(x => Name(x) == name) ?? [];
    static string Value(XElement? e, string name) => Items(e, name).FirstOrDefault()?.Value ?? "";
    static XElement? Chunk(XElement e, string name) => e.Element("chunks")?.Elements("chunk").FirstOrDefault(x => Name(x) == name);
    static string Text(JsonElement e, string key) => e.TryGetProperty(key, out var v) && v.ValueKind == JsonValueKind.String ? v.GetString()! : "";
    static string Limited(JsonElement e, string key, int max) { var s = Text(e, key); if (s.Length > max) throw new Exception("Edit text is too long."); return s; }
    static double? OptionalNumber(JsonElement e, string key) { if (!e.TryGetProperty(key, out var v) || v.ValueKind == JsonValueKind.Null) return null; if (!v.TryGetDouble(out var n) || !double.IsFinite(n)) throw new Exception("Edit values must be finite numbers."); return n; }
    static int Integer(JsonElement e, string key) { var n = OptionalNumber(e,key); if (n == null || n < 0 || n > 127 || Math.Truncate(n.Value) != n) throw new Exception("Invalid port index."); return (int)n; }
    static double Number(XElement e, string key) => double.Parse(Value(e,key), CultureInfo.InvariantCulture);
    static void Set(XElement e, string name, double value) => Set(e, name, value.ToString("R", CultureInfo.InvariantCulture), "gh_double", 6);
    static void Set(XElement e, string name, string value, string type, int code)
    {
        var item = Items(e,name).FirstOrDefault();
        if (item != null) { item.Value = value; return; }
        if (e.Element("items") == null) e.AddFirst(new XElement("items"));
        e.Element("items")!.Add(new XElement("item", new XAttribute("name",name), new XAttribute("type_name",type), new XAttribute("type_code",code), value));
    }
    static XElement[] Ports(XElement c, bool output) => (Chunk(c,"ParameterData") ?? c).Element("chunks")?.Elements("chunk").Where(x => output ? Name(x) is "param_output" or "OutputParam" : Name(x) is "param_input" or "InputParam").OrderBy(x => int.TryParse((string?)x.Attribute("index"),out var i) ? i : 0).ToArray() ?? [];
    static XElement Input(XElement c, int index) { var ports = Ports(c,false); if (ports.Length == 0 && Ports(c,true).Length == 0 && index == 0 && Chunk(c,"Slider") == null && !Items(c,"ToggleValue").Any()) return c; if (index >= ports.Length) throw new Exception("Input port does not exist."); return ports[index]; }
    static string Output(XElement c, int index) { var ports = Ports(c,true); if (ports.Length == 0 && Ports(c,false).Length == 0 && index == 0) return Value(c,"InstanceGuid"); if (index >= ports.Length) throw new Exception("Output port does not exist."); var id = Value(ports[index],"InstanceGuid"); if (!Guid.TryParse(id,out _)) throw new Exception("Output port has no saved GUID."); return id; }
    static void Sources(XElement c, IEnumerable<string> sources)
    {
        var values = sources.Distinct().ToArray();
        foreach (var s in Items(c,"Source").ToArray()) s.Remove();
        Set(c,"SourceCount",values.Length.ToString(),"gh_int32",3);
        for (var i = 0; i < values.Length; i++) c.Element("items")!.Add(new XElement("item",new XAttribute("name","Source"),new XAttribute("index",i),new XAttribute("type_name","gh_guid"),new XAttribute("type_code",9),values[i]));
    }
}
