"use client";
import { useState, useRef } from "react";
import AIStudio from "./AIStudio.jsx";
import fixture from "../tests/fixtures/designer-preview.json";
import {
  emptyBrand,
  emptySpecification,
  reconcileRequirements,
} from "../lib/app-capabilities.js";
const controls = fixture.controls.map((c) => ({
  binding: c.instanceId || c.name,
  label: c.label,
  help:
    c.kind === "number"
      ? "Adjust this dimension to explore the form."
      : "An optional detail for your study.",
}));
const blueprint = reconcileRequirements({
  title: "A form. Your way.",
  description:
    "Explore the proportions, add the details, and make this small geometric study your own.",
  audience: "Designers",
  theme: "paper",
  accent: "green",
  arrangement: "model",
  confidence: "medium",
  reasoning:
    "The saved graph combines a geometric study with editable dimensions and optional text. Two steps separate the shape decisions from the details.",
  questions: ["What does your audience need to compare?"],
  warnings: [
    "Illustrative preview; this plan was not generated by a live model.",
  ],
  workflow: { review: true, pdf: true, assemblyRequested: true },
  brand: { ...emptyBrand(), name: "Sample design studio" },
  specification: emptySpecification(),
  requirements: [],
  steps: [
    {
      id: "proportions",
      title: "Find the proportions",
      description:
        "Start with the overall shape. Small changes can make a big difference.",
      evidence: [],
      controls: controls.filter((_, i) => i < 2),
    },
    {
      id: "details",
      title: "Make it yours",
      description: "Set the finishing details before generating your model.",
      evidence: [],
      controls: controls.filter((_, i) => i >= 2),
    },
  ],
});
export default function AIStudioPreview() {
  const [values, setValues] = useState(() =>
      Object.fromEntries(fixture.controls.map((c) => [c.name, c.value])),
    ),
    [objects, setObjects] = useState([]),
    [solved, setSolved] = useState(null);
  const record = useRef({
    id: "preview",
    revision: 1,
    blueprint,
    definition: fixture,
    conversation: [
      {
        role: "user",
        text: "Build a configurator with review, confirmation and a PDF. Ask me for the missing information.",
      },
      {
        role: "assistant",
        text: "The configuration and PDF workflow is ready. What units, material and connections should the document record? Brand settings are provisional.",
      },
    ],
  });
  const [start, setStart] = useState(true);
  async function request(path, b) {
    if (path === "apps")
      return [{ ...record.current, filename: fixture.filename }];
    if (path.endsWith("save")) {
      record.current = {
        ...record.current,
        revision: record.current.revision + 1,
        blueprint: b.blueprint,
      };
      return record.current;
    }
    if (path.endsWith("generate")) {
      record.current = {
        ...record.current,
        revision: record.current.revision + 1,
        conversation: [
          ...record.current.conversation,
          { role: "user", text: b.prompt },
          {
            role: "assistant",
            text: "Saved the new request. This local preview simulates AI; production uses the real model.",
          },
        ],
      };
      return { ...record.current, geometryUnchanged: true };
    }
    if (path.endsWith("publish"))
      return {
        slug: "preview",
        active: true,
        revision: record.current.revision,
      };
    if (path.endsWith("unpublish")) return {};
    return record.current;
  }
  return (
    <main className="workspace flow-workspace">
      <div className="notice">
        Isolated design preview · simulated AI, storage and geometry · no cloud
        requests.{" "}
        <button className="quiet" onClick={() => setStart(!start)}>
          {start ? "Show draft" : "Show brief"}
        </button>
      </div>
      <AIStudio
        key={String(start)}
        definition={fixture}
        initialApp={start ? null : record.current}
        values={values}
        objects={objects}
        solvedValues={solved}
        onChange={(n, v) => setValues((p) => ({ ...p, [n]: v }))}
        onRun={() => {
          setObjects(fixture.objects);
          setSolved({ ...values });
        }}
        canRun
        member
        onSignIn={() => {}}
        onManual={() => {}}
        onOpen={() => setStart(false)}
        request={request}
      />
    </main>
  );
}
